{{- if .Values.metrics.enabled }}
{{- if .Values.cdc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "milvus.cdc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
    component: "cdc"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: metrics
  selector:
{{ include "milvus.matchLabels" . | indent 4 }}
    component: "cdc"
{{- end }}
{{- end }}
